CREATE TABLE IF NOT EXISTS raw_data (
    id UInt64,
    customer_first_name String,
    customer_last_name String,
    customer_age UInt8,
    customer_email String,
    customer_country String,
    customer_postal_code Nullable(String),
    customer_pet_type String,
    customer_pet_name String,
    customer_pet_breed String,
    seller_first_name String,
    seller_last_name String,
    seller_email String,
    seller_country String,
    seller_postal_code Nullable(String),
    product_name String,
    product_category String,
    product_price Float64,
    product_quantity UInt32,
    sale_date Date,
    sale_customer_id UInt64,
    sale_seller_id UInt64,
    sale_product_id UInt64,
    sale_quantity UInt32,
    sale_total_price Float64,
    store_name String,
    store_location String,
    store_city String,
    store_state Nullable(String),
    store_country String,
    store_phone String,
    store_email String,
    pet_category String,
    product_weight Float64,
    product_color String,
    product_size String,
    product_brand String,
    product_material String,
    product_description String,
    product_rating Float32,
    product_reviews UInt32,
    product_release_date Date,
    product_expiry_date Date,
    supplier_name String,
    supplier_contact String,
    supplier_email String,
    supplier_phone String,
    supplier_address String,
    supplier_city String,
    supplier_country String
) ENGINE = MergeTree()
ORDER BY (id);


INSERT INTO raw_data
SELECT
    id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    parseDateTimeBestEffort(sale_date),
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    parseDateTimeBestEffort(product_release_date),
    parseDateTimeBestEffort(product_expiry_date),
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM file('MOCK_DATA ({0,1,2,3,4}).csv', CSVWithNames);

